/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zamzam_chat_util_FileUtils */

#ifndef _Included_com_zamzam_chat_util_FileUtils
#define _Included_com_zamzam_chat_util_FileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zamzam_chat_util_FileUtils
 * Method:    getFileDescriptorOwner
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_com_zamzam_chat_util_FileUtils_getFileDescriptorOwner
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_zamzam_chat_util_FileUtils
 * Method:    createMemoryFileDescriptor
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zamzam_chat_util_FileUtils_createMemoryFileDescriptor
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
